FROM public.ecr.aws/docker/library/alpine:edge

ARG WP_VERSION

RUN apk add -u --no-cache \
	composer \
	curl \
	git \
	imagemagick \
	mysql \
	mysql-client \
	php85 \
	php85-curl \
	php85-dom \
	php85-exif \
	php85-mysqli \
	php85-pecl-imagick \
	php85-simplexml \
	php85-tokenizer \
	php85-xml \
	php85-xmlwriter

RUN apk add --no-cache php85-pear php85-dev gcc musl-dev make \
	&& pecl85 install pcov && echo extension=pcov.so > /etc/php85/conf.d/pcov.ini \
	&& apk del php85-pear php85-dev gcc musl-dev make

# Create php symlink to php85
RUN ln -sf /usr/bin/php85 /usr/bin/php

RUN curl -fsSL -o /tmp/wordpress.tar.gz https://wordpress.org/wordpress-${WP_VERSION}.tar.gz \
	&& mkdir /wordpress \
	&& tar --strip-components=1 -zxmf /tmp/wordpress.tar.gz -C /wordpress \
	&& rm /tmp/wordpress.tar.gz

RUN curl -fsSL -o /tmp/wp-phpunit.tar.gz https://github.com/wp-phpunit/wp-phpunit/archive/${WP_VERSION}.0.tar.gz \
	&& mkdir /wp-phpunit \
	&& tar --strip-components=1 -zxmf /tmp/wp-phpunit.tar.gz -C /wp-phpunit \
	&& rm /tmp/wp-phpunit.tar.gz

RUN mysql_install_db --user=mysql --ldata=/var/lib/mysql
RUN sh -c 'mysqld_safe --datadir=/var/lib/mysql &' && sleep 4 && mysql -u root -e "CREATE DATABASE wordpress"

ENV WP_DEVELOP_DIR=/wp-phpunit
ENV WP_PHPUNIT__TESTS_CONFIG=/wp-tests-config.php

VOLUME ["/code"]
WORKDIR /code
COPY ./docker-entrypoint.sh /entrypoint.sh
COPY ./wp-tests-config.php /wp-tests-config.php
RUN chmod 755 /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
