FROM public.ecr.aws/docker/library/alpine:3.21

ARG WP_VERSION

RUN apk add -u --no-cache \
	composer \
	curl \
	git \
	imagemagick \
	mysql \
	mysql-client \
	php84 \
	php84-curl \
	php84-dom \
	php84-exif \
	php84-mysqli \
	php84-pecl-imagick \
	php84-simplexml \
	php84-tokenizer \
	php84-xml \
	php84-xmlwriter

RUN apk add --no-cache php84-pear php84-dev gcc musl-dev make \
	&& pecl84 install pcov && echo extension=pcov.so > /etc/php84/conf.d/pcov.ini \
	&& apk del php84-pear php84-dev gcc musl-dev make

# Create php symlink to php84
RUN ln -sf /usr/bin/php84 /usr/bin/php

RUN curl -fsSL -o /tmp/wordpress.tar.gz https://wordpress.org/wordpress-${WP_VERSION}.tar.gz \
	&& mkdir /wordpress \
	&& tar --strip-components=1 -zxmf /tmp/wordpress.tar.gz -C /wordpress \
	&& rm /tmp/wordpress.tar.gz

RUN curl -fsSL -o /tmp/wp-phpunit.tar.gz https://github.com/wp-phpunit/wp-phpunit/archive/${WP_VERSION}.0.tar.gz \
	&& mkdir /wp-phpunit \
	&& tar --strip-components=1 -zxmf /tmp/wp-phpunit.tar.gz -C /wp-phpunit \
	&& rm /tmp/wp-phpunit.tar.gz

RUN mysql_install_db --user=mysql --ldata=/var/lib/mysql
RUN sh -c 'mysqld_safe --datadir=/var/lib/mysql &' && sleep 4 && mysql -u root -e "CREATE DATABASE wordpress"

ENV WP_DEVELOP_DIR=/wp-phpunit
ENV WP_PHPUNIT__TESTS_CONFIG=/wp-tests-config.php

VOLUME ["/code"]
WORKDIR /code
COPY ./docker-entrypoint.sh /entrypoint.sh
COPY ./wp-tests-config.php /wp-tests-config.php
RUN chmod 755 /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
