name: ci

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['8.0', '8.1', '8.2', '8.3']
        wp_version: ['5.4', '5.5', '5.6', '6.8']
        include:
          # Default latest tag with PHP 8.0 and WP 6.8
          - php_version: '8.0'
            wp_version: '6.8'
            is_latest: true
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Generate tags and dockerfile
        id: setup
        run: |
          PHP_SHORT=$(echo "${{ matrix.php_version }}" | tr -d '.')
          if [ "${{ matrix.is_latest }}" == "true" ]; then
            echo "tags=humanmade/plugin-tester:latest,humanmade/plugin-tester:php$PHP_SHORT-wp${{ matrix.wp_version }}" >> $GITHUB_OUTPUT
          else
            echo "tags=humanmade/plugin-tester:php$PHP_SHORT-wp${{ matrix.wp_version }}" >> $GITHUB_OUTPUT
          fi
          echo "dockerfile=Dockerfile.php$PHP_SHORT" >> $GITHUB_OUTPUT
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ steps.setup.outputs.dockerfile }}
          build-args: |
            WP_VERSION=${{ matrix.wp_version }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ steps.setup.outputs.tags }}
